# -*- coding: utf-8 -*-
"""4110E115_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENuKSTPh9VjwUx27TaZBppKeucRwlyxN
"""

x = input("please enter your old:")
print(x)

x = 6
y = 976.045
z = 1j
print(x)
print(y)
print(z)

x = 567
y = 97.764
z = 3j
type(x, y, z)

dict = {"name":"alita","old":2,"country":"taiwan"}
print(dict)

mylist =["book","pen","money",986]
print(mylist)
type(mylist)

mytuple = ("cat","dog","fish")
print(mytuple)
type(mytuple)

mytuple = "cat","dog","fish"
print(mytuple)
a, b, c = mytuple
print(a)
print(b)
print(c)
type(mytuple)

x = int(214.76)
y = float(234)
print(x)
print(y)

x = "hello, this is 4110e115 Pan Huang Ru from Kunshan university
nice to meet you guy"
print(x)

x = '''hello, this is 4110e115 Pan Huang Ru from Kunshan university
nice to meet you guy'''
print(x)

x = "Pan Huang Ru"
print(x[0:12])
print(x[-12:-1])
print(x[-12:])
print(x[-8:-4])

x = "pan huang ru"
print(x.upper())
y = "PAN HUANG RU"
print(y.lower())

x = "   Pan Huang Ru   "
y = "   Pan Huang Ru    "
print(x.strip())
print(y)

x = "Pan"
y = "Huang"
z = "ru"
print(x+y+z)
print(x+" "+y+" "+z)

x = int(input("enter your old:"))
if x > 25:
 print("older")
elif x == 25:
 print("equal")
else:
 print("younger")

x = "beautiful\n"
n = 6
print(x*n)

x = 8
y = 3
print(x/y)
print(x//y)

x = 8
y = 3
print(x/y)
print(x%y)
print(x+y)
print(x*y)
print(x-y)

mylist = ["house","car","money"]
for x in mylist:
 print(x)
for y in "money":
 print(y)

mylist = ["house","car","money"]
for x in mylist:
  print(x)
  if x == "car":
    break

mylist = ["house","car","money"]
for x in mylist:
  print(x)
  if x == "house":
    continue

for x in range(2, 10, 1):
  print(x)
for y in range(2, 10, 2):
  print(y)

for x in range(3):
  print(x)
else:
  print("donedone")

x = 1
while x < 5:
  print(x)
  x += 1